def menu():
    print("\nAvailable Commands:")
    print("1. Create Branch")
    print("2. Get Branch by ID")
    print("3. Create Supplier")
    print("4. Get Supplier by ID")
    print("5. Create Customer")
    print("6. Get Customer by ID")
    print("7. See Customer's Branches")
    print("8. Add Customer to a Branch")
    print("9. Add Supplier to a Branch")
    print("10. See Suppliers in a Branch")
    print("11. See Branches of a Supplier")
    print("12. Exit")
    return None